import type { VercelRequest, VercelResponse } from '@vercel/node';
import nodemailer from 'nodemailer';
import { checkRateLimit, getClientIp } from './_rate-limit.js';

const RATE_LIMIT = { windowMs: 60_000, maxRequests: 3 };

const SMTP_HOST = 'mail.privateemail.com';
const SMTP_PORT = 587;
const SMTP_USER = 'signal@shapeneural.com';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS: allow from anywhere (called from user scripts)
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const clientIp = getClientIp(req);
  const rateCheck = checkRateLimit(clientIp, RATE_LIMIT);
  if (!rateCheck.allowed) {
    res.setHeader('Retry-After', Math.ceil((rateCheck.retryAfterMs || 1000) / 1000));
    return res.status(429).json({ error: 'Too many requests. Try again later.' });
  }

  const smtpPassword = process.env.SMTP_PASSWORD;
  if (!smtpPassword) return res.status(500).json({ error: 'SMTP not configured' });

  try {
    const { content, to, subject, email } = req.body;
    if (!content || !to || !subject) {
      return res.status(400).json({ error: 'content, to, and subject are required' });
    }

    console.log(`[forge-deliver] Sending to ${to} from ${email || 'unknown'} (${clientIp})`);

    const transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: SMTP_PORT,
      secure: false, // STARTTLS on port 587
      auth: {
        user: SMTP_USER,
        pass: smtpPassword,
      },
    });

    await transporter.sendMail({
      from: `"AUTOFORGE" <${SMTP_USER}>`,
      to,
      subject,
      html: `
        <div style="font-family: 'Courier New', monospace; background: #0a0a0a; color: #e0e0e0; padding: 32px; max-width: 600px;">
          <div style="border-bottom: 1px solid #333; padding-bottom: 16px; margin-bottom: 24px;">
            <span style="color: #00ff41; font-size: 12px; letter-spacing: 3px;">AUTOFORGE // PIPELINE OUTPUT</span>
          </div>
          <div style="white-space: pre-wrap; line-height: 1.7; font-size: 14px;">${content}</div>
          <div style="border-top: 1px solid #333; padding-top: 16px; margin-top: 24px;">
            <span style="color: #666; font-size: 11px; letter-spacing: 2px;">Generated by AUTOFORGE — shapeneural.com/forge</span>
          </div>
        </div>
      `,
      text: content, // Plain text fallback
    });

    return res.status(200).json({ success: true });
  } catch (error) {
    console.error('Forge deliver error:', error);
    return res.status(500).json({
      error: 'Email delivery failed',
      details: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
